package zinc.ui;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Random;

import org.junit.jupiter.api.Test;

/** Tests Zinc's randomized personality responses and their factual content. */
public class UiTest {
    @Test
    void responseGetters_fixedVariant_returnExpectedPersonalityLines() {
        Ui ui = new Ui(new FixedIndexRandomGenerator(2));

        assertEquals("Hello! Let's tune up your day together.", ui.getGreetingMessage());
        assertEquals("What shall we rock through next?", ui.getConversationPrompt());
        assertEquals("Goodbye. The stage is yours!", ui.getGoodbyeMessage());
    }

    @Test
    void printTaskList_fixedVariant_preservesHeadingAndEntries() {
        Ui ui = new Ui(new FixedIndexRandomGenerator(0));

        String output = captureOutput(() -> ui.printTaskList(
                "Here are your current tasks:", List.of("1. [T][ ] Tune guitar")));

        assertTrue(output.contains("Here comes the setlist!"));
        assertTrue(output.contains("Here are your current tasks:"));
        assertTrue(output.contains("1. [T][ ] Tune guitar"));
    }

    @Test
    void printSuccessAndError_fixedVariant_preserveCommandDetails() {
        Ui ui = new Ui(new FixedIndexRandomGenerator(1));

        String output = captureOutput(() -> {
            ui.printTaskAdded("[T][ ] Practice scales", 3);
            ui.printTaskNumberError("mark");
            ui.printTaskNumberTooLarge("delete");
        });

        assertTrue(output.contains("Nice riff!"));
        assertTrue(output.contains("You have 3 tasks in the list"));
        assertTrue(output.contains("Let's tune that command."));
        assertTrue(output.contains("Usage: mark <task number>"));
        assertTrue(output.contains("Task number is too large. Usage: delete <task number>"));
    }

    @Test
    void printHelp_fixedVariant_displaysCompactCommandOverview() {
        Ui ui = new Ui(new FixedIndexRandomGenerator(2));

        String output = captureOutput(ui::printHelp);

        assertTrue(output.contains("These commands are ready to rock:"));
        assertTrue(output.contains("Available commands:"));
        assertTrue(output.contains("Tasks: todo, deadline, event, list, find, mark, unmark, delete"));
        assertTrue(output.contains("Contacts: contact add, contact delete, contact update, contact list"));
        assertTrue(output.contains("General: help, ui background, bye"));
        assertFalse(output.contains("Usage:"));
    }

    @Test
    void printedMessages_multipleUiActions_omitHorizontalSeparators() {
        Ui ui = new Ui(new FixedIndexRandomGenerator(0));

        String output = captureOutput(() -> {
            ui.printGreeting();
            ui.printTaskAdded("[T][ ] Practice scales", 1);
            ui.printTaskList("Here are your current tasks:", List.of("1. [T][ ] Practice scales"));
            ui.printGoodbye();
        });

        assertFalse(output.contains("_"));
    }

    /** Captures standard output generated by one UI action. */
    private String captureOutput(Runnable action) {
        PrintStream originalOutput = System.out;
        ByteArrayOutputStream capturedOutput = new ByteArrayOutputStream();
        System.setOut(new PrintStream(capturedOutput, true, StandardCharsets.UTF_8));
        try {
            action.run();
        } finally {
            System.setOut(originalOutput);
        }
        return capturedOutput.toString(StandardCharsets.UTF_8);
    }

    /** A random generator that always chooses one requested response index. */
    private static class FixedIndexRandomGenerator extends Random {
        private static final long serialVersionUID = 1L;

        /** The response index returned whenever it is within the supplied bound. */
        private final int responseIndex;

        FixedIndexRandomGenerator(int responseIndex) {
            this.responseIndex = responseIndex;
        }

        @Override
        public int nextInt(int bound) {
            return Math.min(responseIndex, bound - 1);
        }
    }
}
