package zinc;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import zinc.contact.ContactList;
import zinc.task.TaskList;
import zinc.ui.BackgroundType;
import zinc.ui.CommandParser;
import zinc.ui.Ui;

/** Runs the Zinc task-management application. */
public class Zinc {
    /** The warning shown when saved task data cannot be parsed. */
    private static final String CORRUPTED_TASK_DATA_WARNING =
            "NOTE: Your saved task data has been corrupted. Zinc started with an empty task list.\n";

    /** The warning shown when saved contact data cannot be parsed. */
    private static final String CORRUPTED_CONTACT_DATA_WARNING =
            "NOTE: Your saved contact data has been corrupted. Zinc started with an empty contact list.\n";

    /** The UI shared by all commands in this Zinc instance. */
    private final Ui ui;

    /** The task list shared by all commands in this Zinc instance. */
    private final TaskList taskList;

    /** The contact list shared by all commands in this Zinc instance. */
    private final ContactList contactList;

    /** The command parser used by this Zinc instance. */
    private final CommandParser commandParser;

    /** Warnings that should be displayed when a graphical interface starts. */
    private final List<String> startupWarnings;

    /** Creates a Zinc instance with task, contact, command, and UI components. */
    public Zinc() {
        ui = new Ui();
        taskList = new TaskList(ui);
        contactList = new ContactList(ui);
        commandParser = new CommandParser(taskList, contactList, ui);
        startupWarnings = createStartupWarnings();
    }

    /**
     * Processes one command and returns the response generated by Zinc.
     * Standard output is captured because the command handlers are shared with the terminal interface.
     *
     * @param input The command entered by the user.
     * @return The response generated while processing the command.
     */
    public String processCommand(String input) {
        ByteArrayOutputStream response = new ByteArrayOutputStream();
        PrintStream originalOutput = System.out;

        try (PrintStream capturedOutput = new PrintStream(response, true, StandardCharsets.UTF_8)) {
            System.setOut(capturedOutput);
            commandParser.parseCommand(input);
        } finally {
            System.setOut(originalOutput);
        }

        return response.toString(StandardCharsets.UTF_8).trim();
    }

    /**
     * Returns a randomly selected greeting for a user interface.
     * Notifies the user if data is corrupted.
     *
     * @return A friendly greeting.
     */
    public String getGreetingResponse() {
        if (startupWarnings.isEmpty()) {
            return ui.getGreetingMessage();
        }

        return ui.getGreetingMessage() + startupWarnings.stream().reduce("\n", String::concat);
    }

    /**
     * Returns a randomly selected prompt for a fresh conversation.
     *
     * @return A friendly conversation prompt.
     */
    public String getConversationPromptResponse() {
        return ui.getConversationPrompt();
    }

    /**
     * Returns a randomly selected goodbye message for a user interface.
     *
     * @return A friendly goodbye message.
     */
    public String getGoodbyeResponse() {
        return ui.getGoodbyeMessage();
    }

    /**
     * Returns warnings detected while restoring saved application data.
     *
     * @return An immutable list of warnings to display during startup.
     */
    public List<String> getStartupWarnings() {
        return startupWarnings;
    }

    /** Returns the background selection currently used by the graphical interface. */
    public BackgroundType getBackgroundType() {
        return ui.getBackgroundType();
    }

    /** Creates the warnings for data corruption detected during construction. */
    private List<String> createStartupWarnings() {
        List<String> warnings = new ArrayList<>();
        if (taskList.wasStoredDataCorrupted()) {
            warnings.add(CORRUPTED_TASK_DATA_WARNING);
        }
        if (contactList.wasStoredDataCorrupted()) {
            warnings.add(CORRUPTED_CONTACT_DATA_WARNING);
        }
        return List.copyOf(warnings);
    }

    /**
     * Starts Zinc and handles terminal input until the user enters {@code bye}.
     * Enter {@code list} to display all previously stored tasks.
     *
     * @param args Command-line arguments, which are not used.
     */
    public static void main(String[] args) {
        Zinc zinc = new Zinc();
        Ui ui = zinc.ui;
        ui.printBanner();
        ui.printGreeting();

        Scanner scanner = new Scanner(System.in);

        while (scanner.hasNextLine()) {
            String userInput = scanner.nextLine();
            boolean shouldExit = zinc.commandParser.parseCommand(userInput);
            if (shouldExit) {
                break;
            }
        }

        ui.printGoodbye();
    }
}
