package zinc;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.Scanner;

import zinc.task.InputList;
import zinc.ui.Parser;
import zinc.ui.Ui;

/** Runs the Zinc task-management application. */
public class Zinc {
    /** The task list shared by all commands in this Zinc instance. */
    private final InputList inputs = new InputList();

    /** The command parser used by this Zinc instance. */
    private final Parser parser = new Parser(inputs);

    /**
     * Processes one command and returns the response generated by Zinc.
     *
     * @param input The command entered by the user.
     * @return The response generated while processing the command.
     */
    public String getResponse(String input) {
        ByteArrayOutputStream response = new ByteArrayOutputStream();
        PrintStream originalOutput = System.out;

        try (PrintStream capturedOutput = new PrintStream(response)) {
            System.setOut(capturedOutput);
            parser.parse(input);
        } finally {
            System.setOut(originalOutput);
        }

        return response.toString().trim();
    }

    /**
     * Starts Zinc and handles terminal input until the user enters {@code bye}.
     * Enter {@code list} to display all previously stored tasks.
     *
     * @param args Command-line arguments, which are not used.
     */
    public static void main(String[] args) {
        Ui ui = new Ui();
        ui.printBanner();
        ui.printGreeting();

        Scanner scanner = new Scanner(System.in);
        Zinc zinc = new Zinc();

        while (!zinc.parser.parse(scanner.nextLine())) {}

        ui.printGoodbye();
    }
}
