package zinc;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;

import zinc.contact.ContactList;
import zinc.task.TaskList;
import zinc.ui.CommandParser;
import zinc.ui.Ui;

/** Runs the Zinc task-management application. */
public class Zinc {
    /** The task list shared by all commands in this Zinc instance. */
    private final TaskList taskList = new TaskList();

    /** The contact list shared by all commands in this Zinc instance. */
    private final ContactList contactList = new ContactList();

    /** The command parser used by this Zinc instance. */
    private final CommandParser commandParser = new CommandParser(taskList, contactList);

    /**
     * Processes one command and returns the response generated by Zinc.
     * Standard output is captured because the command handlers are shared with the terminal interface.
     *
     * @param input The command entered by the user.
     * @return The response generated while processing the command.
     */
    public String processCommand(String input) {
        ByteArrayOutputStream response = new ByteArrayOutputStream();
        PrintStream originalOutput = System.out;

        try (PrintStream capturedOutput = new PrintStream(response, true, StandardCharsets.UTF_8)) {
            System.setOut(capturedOutput);
            commandParser.parseCommand(input);
        } finally {
            System.setOut(originalOutput);
        }

        return response.toString(StandardCharsets.UTF_8).trim();
    }

    /**
     * Starts Zinc and handles terminal input until the user enters {@code bye}.
     * Enter {@code list} to display all previously stored tasks.
     *
     * @param args Command-line arguments, which are not used.
     */
    public static void main(String[] args) {
        Ui ui = new Ui();
        ui.printBanner();
        ui.printGreeting();

        Scanner scanner = new Scanner(System.in);
        Zinc zinc = new Zinc();

        while (scanner.hasNextLine()) {
            String userInput = scanner.nextLine();
            boolean shouldExit = zinc.commandParser.parseCommand(userInput);
            if (shouldExit) {
                break;
            }
        }

        ui.printGoodbye();
    }
}
